import streamlit as st
import requests
import json
import os
import glob
import pandas as pd
from datetime import datetime

st.set_page_config(page_title="IntelligenceStack", layout="wide", initial_sidebar_state="expanded")

# Custom CSS for Premium Executive Look
st.markdown("""
<style>
    /* Global styling */
    .stApp {
        background-color: #0d1117;
        color: #c9d1d9;
        font-family: 'Inter', sans-serif;
    }
    
    /* Headers */
    h1, h2, h3 {
        color: #ff6c00 !important; /* Databricks Orange */
        font-weight: 600 !important;
    }
    
    /* Chat bubbles */
    .stChatMessage {
        background-color: rgba(255, 255, 255, 0.05);
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 12px;
        padding: 15px;
        margin-bottom: 10px;
        backdrop-filter: blur(10px);
    }
    
    /* Sidebar styling */
    .css-1d391kg {
        background-color: #161b22;
        border-right: 1px solid rgba(255, 255, 255, 0.1);
    }
    
    /* Metrics */
    div[data-testid="stMetricValue"] {
        color: #ff6c00 !important;
    }
</style>
""", unsafe_allow_html=True)

# Sidebar
with st.sidebar:
    st.image("https://upload.wikimedia.org/wikipedia/commons/6/63/Databricks_Logo.png", width=200)
    st.markdown("## IntelligenceStack Control Plane")
    st.markdown("---")
    st.toggle("Lakehouse AI Gateway", value=True, disabled=True)
    st.toggle("Liquid Clustering Active", value=True, disabled=True)
    st.toggle("Unity Catalog Strict Mode", value=True, disabled=True)
    
    st.markdown("### System Health")
    st.success("All systems operational.")

st.title("🛡️ IntelligenceStack Control Plane")
st.markdown("---")

tab1, tab2, tab3 = st.tabs(["🤖 Cognitive Agent", "📊 Live Telemetry", "🏛️ Architecture"])

with tab1:
    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []

    for entry in st.session_state.chat_history:
        with st.chat_message(entry["role"]):
            st.markdown(entry["content"])

    if prompt_input := st.chat_input("Enter your structural query (e.g., 'Evaluate anomaly parameters for customer CUST_404')"):
        st.session_state.chat_history.append({"role": "user", "content": prompt_input})
        with st.chat_message("user"):
            st.markdown(prompt_input)
            
        with st.chat_message("assistant"):
            with st.spinner("Traversing physical Delta structures and verifying tool metadata..."):
                try:
                    network_response = requests.post(
                        "http://localhost:8000/api/v1/agent/explore",
                        json={"prompt": prompt_input},
                        timeout=45
                    )
                    if network_response.status_code == 200:
                        output = network_response.json()
                        st.markdown(output["data"])
                        
                        # Trace Log Visulization
                        with st.expander("🔍 View Agent Trace Route"):
                            for trace in output.get("trace_log", []):
                                st.markdown(f"**[{trace['status']}] {trace['step']}**: {trace['detail']}")
                        
                        st.caption(f"**Security Assurance:** {output['governance_metadata']}")
                        st.session_state.chat_history.append({"role": "assistant", "content": output["data"]})
                    else:
                        st.error(f"Remote server emitted bad status packet: {network_response.text}")
                except Exception as ex:
                    st.error(f"Failed to route network payload to API Gateway: {str(ex)}")

with tab2:
    st.markdown("### Streaming Ingestion Pipeline")
    
    # Read the JSON logs generated by synthetic_generator.py
    log_dir = "/Users/atharvvani/Downloads/DataBricks/mnt/telemetry/raw_logs"
    all_events = []
    
    try:
        files = glob.glob(os.path.join(log_dir, "*.json"))
        for file in files:
            with open(file, 'r') as f:
                for line in f:
                    if line.strip():
                        all_events.append(json.loads(line))
    except Exception as e:
        st.warning(f"Could not load telemetry data: {e}")
        
    if all_events:
        df = pd.DataFrame(all_events)
        df['latency'] = df['context'].apply(lambda x: x.get('latency', 0))
        
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Events Ingested", f"{len(df):,}")
        col2.metric("Avg Latency (ms)", f"{df['latency'].mean():.2f}")
        col3.metric("Anomalies Detected", f"{len(df[df['latency'] > 400])}")
        
        st.markdown("#### Real-time Latency Distribution")
        # Ensure timestamp is datetime and sort
        df['timestamp'] = pd.to_datetime(df['timestamp'])
        df = df.sort_values('timestamp')
        st.line_chart(df.set_index('timestamp')['latency'])
        
        st.markdown("#### Raw Delta Live Tables Feed")
        st.dataframe(df[['timestamp', 'customer_id', 'event_type', 'latency']].tail(10))
    else:
        st.info("No live telemetry data found. Start the synthetic generator to view real-time metrics.")

with tab3:
    st.markdown("### Databricks Reference Architecture")
    st.image("/Users/atharvvani/Downloads/DataBricks/architecture_diagram.png", use_container_width=True)
